### ISSUE TITLE
 Documentation Update Needed on Default Branch Naming (`main` vs `master`)

### ISSUE THREAD

**Issue by gowthamtirri** [Writesonic/GPTRouter#14]
#### Context
I noticed a discrepancy between the contribution guidelines in the documentation and the actual branch structure in the repository. The guidelines reference a `master` branch for pull requests, but the repository uses `main` as its default branch.

#### Issue
This inconsistency could lead to confusion for new contributors who are following the contribution process outlined in the documentation.

### Suggestion/Query

Option 1: **Documentation Update**
I suggest updating the documentation to reflect the current branch structure of the repository. Specifically, replacing instances of `master` with `main` in the contribution guidelines would align it with the actual branch used and clarify the process for new contributors.

Option 2: **Branch Re-Naming**
Is there an intention to update the repository's default branch to `master` to align with the current documentation? If not, would it be beneficial to update the documentation to reference the `main` branch instead?

### Additional Notes
I came across this while preparing to contribute to the project. Ensuring consistency between the documentation and the actual repository setup would be helpful for new contributors.

Thank you for addressing this issue.

**Comment by samanyougarg** [comment]
Closed in #15
